### ISSUE TITLE
service script not working

### ISSUE THREAD

**Issue by ddepaoli3** [telefonicaid/fiware-monitoring#49]
Ubuntu 14.04 64 bit.
fiware-monitoring develop branch
build package with script
Install package with dpkg -i
When launch ```service ngsi_adapter start``` it returns:

```
/etc/init.d/ngsi_adapter: 1: /etc/profile.d/umm.sh: umm: not found
/etc/init.d/ngsi_adapter: 1: [: z: unexpected operator
```

**Comment by ddepaoli3** [comment]
Solved changing ```/bin/sh``` to ```/bin/bash```  at line 1 in /etc/init.d/ngsi_adapter

**Comment by pratid** [comment]
All scripts are deliberately prepared to run with the standard "sh" shell (avoiding any extension introduced by the Bourne Again Shell "bash"), so this change is unnecessary.

If you take a look at line [29](https://github.com/telefonicaid/fiware-monitoring/blob/develop/ngsi_adapter/script/build/files/debian/ngsi_adapter.init#L29), the service script loads the system-wide *.profile* file for the **sh** shell (`/etc/profile`), which in turn loads any file `*.sh` found at `/etc/profile.d/`. One of these files is that `umm.sh` mentioned in your comment, which apparently uses bash extensions not recognized by sh.

Altering the service init script to use bash as interpreter is a valid workaround, but the correct solution would be moving any bash-specific initialization elsewhere, keeping everything under `/etc/profile.d/` strictly sh-compliant.
