### ISSUE TITLE
'ngsi_event_broker_xifi.so' is using an old or unspecified version of the event broker API

### ISSUE THREAD

**Issue by oalifdal** [telefonicaid/fiware-monitoring#64]
I am trying to integrate the Monitoring GE into our infrastructure. We already use Nagios 4.0.7 for monitoring a number of hosts and services.
I installed the package fiware-monitoring-ngsi-event-broker from the debian repository.

When I configure broker_module as stated in the documentation and launch Nagios, I get the following error:
```
Error: Module '/opt/fiware/ngsi_event_broker/lib/ngsi_event_broker_xifi.so' is using an old or unspecified version of the event broker API.  Module will be unloaded.
```

I suspect the ngsi-event-broker to be incompatible with Nagios 4.
Is there a way to use the event broker with Nagios 4?

Thanks!

**Comment by flopezag** [comment]
Dear Omar,

We have to evaluate the case that you provide in order to see the compatibility with this version. Currently I cannot give you more details. Nevertheless, if you discover how to use it with Nagios 4 before we do it, you are welcome to integrate it into the repository.

Fernando

**Comment by oalifdal** [comment]
Hi Fernando, thank you for the prompt reply! I will let you know how it goes.

Now I tried compiling from the source (with Nagios 3.5.1 now as per the documentation, my idea is to try with Nagios 4 after this works), but I'm getting the following error:

```
hupp@beta:~/fiware/monitoring-ng3/fiware-monitoring/ngsi_event_broker$ make
Making all in src
make[1]: Entering directory `/home/hupp/fiware/monitoring-ng3/fiware-monitoring/ngsi_event_broker/src'
make  all-am
make[2]: Entering directory `/home/hupp/fiware/monitoring-ng3/fiware-monitoring/ngsi_event_broker/src'
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.  -DNDEBUG -I/home/hupp/fiware/monitoring-ng3/fiware-monitoring/ngsi_event_broker/contrib/nagios/include -Wall
-MT ngsi_event_broker_xifi_la-ngsi_event_broker_common.lo -MD -MP -MF .deps/ngsi_event_broker_xifi_la-ngsi_event_broker_common.Tpo -c -o ngsi_event_broker_xifi_la-ngsi_event_broker_
common.lo `test -f 'ngsi_event_broker_common.c' || echo './'`ngsi_event_broker_common.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -DNDEBUG -I/home/hupp/fiware/monitoring-ng3/fiware-monitoring/ngsi_event_broker/contrib/nagios/include -Wall -MT ngsi_event_broker_xifi_la
-ngsi_event_broker_common.lo -MD -MP -MF .deps/ngsi_event_broker_xifi_la-ngsi_event_broker_common.Tpo -c ngsi_event_broker_common.c  -fPIC -DPIC -o .libs/ngsi_event_broker_xifi_la-n
gsi_event_broker_common.o
ngsi_event_broker_common.c: In function 'find_plugin_command_name':
ngsi_event_broker_common.c:257:53: error: 'service' has no member named 'service_check_command'
   char* service_check_command = strdup(check_service->service_check_command);
                                                     ^
ngsi_event_broker_common.c:270:41: error: 'service' has no member named 'service_check_command'
                            check_service->service_check_command,
                                         ^
make[2]: *** [ngsi_event_broker_xifi_la-ngsi_event_broker_common.lo] Error 1
make[2]: Leaving directory `/home/hupp/fiware/monitoring-ng3/fiware-monitoring/ngsi_event_broker/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/hupp/fiware/monitoring-ng3/fiware-monitoring/ngsi_event_broker/src'
make: *** [all-recursive] Error 1
```

**Comment by pratid** [comment]
Dear Omar

As mentioned, Nagios API has changed in version 4.x. Taking a look at `objects.h` we'll find the problem:

    /* SERVICE structure (Nagios 3.x) */
    struct service_struct {
    	...
    	char    *service_check_command;
    	char    *event_handler;
    	...
    
    
    /* SERVICE structure (Nagios 4.x) */
    struct service {
    	...
    	char    *check_command;
    	char    *event_handler;
    	...


It would be very interesting if you could use the `CURRENT_OBJECT_STRUCTURE_VERSION` macro defined at the same header file to carry out some conditional definitions supporting both Nagios 3.x and 4.x. For example, you could use macros:

    /* ngsi_event_broker_common.h */
    #if (CURRENT_OBJECT_STRUCTURE_VERSION < 400)
    #define SERVICE_CHECK_COMMAND(ptr) (ptr)->service_check_command
    #else
    #define SERVICE_CHECK_COMMAND(ptr) (ptr)->check_command
    #endif
    
    
    /* ngsi_event_broker_common.c */
    ...
    char* service_check_command = strdup(SERVICE_CHECK_COMMAND(check_service));
    ...


Your PRs would be very welcomed.

Regards.
